CREATE TABLE TBL_CARRERAS(
    ID NUMERIC(4) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    ESTADO CHAR(1) NOT NULL
);
 CREATE SEQUENCE SEQ_CARRERAS;
 INSERT INTO TBL_CARRERAS (ID, NOMBRE, ESTADO) VALUES (SEQ_CARRERAS.NEXTVAL, 'SISTEMAS', '1');
 INSERT INTO TBL_CARRERAS (ID, NOMBRE, ESTADO) VALUES (SEQ_CARRERAS.NEXTVAL, 'ARQUITECTURA', '1');
 INSERT INTO TBL_CARRERAS (ID, NOMBRE, ESTADO) VALUES (SEQ_CARRERAS.NEXTVAL, 'AMBIENTAL', '1');
 INSERT INTO TBL_CARRERAS (ID, NOMBRE, ESTADO) VALUES (SEQ_CARRERAS.NEXTVAL, 'ALIMENTOS', '1');
CREATE TABLE TBL_ESTUDIANTES(
    ID            NUMERIC(4) NOT NULL PRIMARY KEY,
    NOMBRES       VARCHAR2(60) NOT NULL UNIQUE,
    APELLIDOS     VARCHAR2(300) NOT NULL,
    DIRECCION	  VARCHAR2(150) NULL,
    EDAD          INTEGER NOT NULL,
    CIUDAD        VARCHAR2(50),
    PAIS          VARCHAR2(50),
    CARRERA_ID NUMERIC(4) REFERENCES TBL_CARRERAS(ID)
 );
 CREATE SEQUENCE SEQ_ESTUDIANTES;
 
INSERT INTO TBL_ESTUDIANTES (ID, NOMBRES, APELLIDOS, DIRECCION, EDAD, CIUDAD, PAIS, CARRERA_ID) VALUES (SEQ_ESTUDIANTES.NEXTVAL, 'GEOVANNY', 'MENDOZA', 'Calle 41 San Jose',28,'Barranquilla', 'Colombia', 1);
INSERT INTO TBL_ESTUDIANTES (ID, NOMBRES, APELLIDOS, DIRECCION, EDAD, CIUDAD, PAIS, CARRERA_ID) VALUES (SEQ_ESTUDIANTES.NEXTVAL, 'OMAR', 'BERROTERAN', 'Bo grenada Casa C22',27,'Managua', 'Nicaragua',2);
COMMIT;
